name: Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install & build frontend
      - name: Build frontend
        working-directory: frontend
        run: |
          mkdir -p build
          npm install
          npm run build

      # Step 4: Prepare deployment package
      - name: Archive project files
        run: |
          mkdir -p deploy/backend deploy/frontend
          cp -r backend/* deploy/backend/
          cp -r frontend/build/* deploy/frontend/
          cd deploy && tar -czf release.tar.gz backend frontend

      # Step 5: Upload to EC2 via SCP
      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "deploy/release.tar.gz"
          target: "~/Apex-Auto/"

      # Step 6: SSH into EC2 and deploy
      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Apex-Auto
            tar -xzf release.tar.gz
            cd backend
            npm install --omit=dev
            pm2 restart apex-backend || pm2 start server.js --name apex-backend
            sudo systemctl restart nginx
