name: Deploy Apex Auto to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and setup on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ~

            echo "=== Updating server ==="
            sudo apt update -y && sudo apt install -y nodejs npm nginx git

            echo "=== Cleaning previous deployment ==="
            sudo rm -rf ~/Apex-Auto
            sudo mkdir -p ~/Apex-Auto
            sudo chown -R ubuntu:ubuntu ~/Apex-Auto

            echo "=== Cloning latest code ==="
            git clone https://github.com/JNilukshan/Apex-Auto.git

            echo "=== Setting up backend ==="
            cd ~/Apex-Auto/backend
            npm install

            echo "=== Writing backend .env ==="
            cat <<EOF > ~/Apex-Auto/backend/.env
            PORT=5000
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

            echo "=== Starting backend with PM2 ==="
            sudo npm install -g pm2
            pm2 stop apex-backend || true
            pm2 start server.js --name apex-backend
            pm2 save
            pm2 startup | sudo bash

            echo "=== Setting up frontend ==="
            cd ~/Apex-Auto/frontend
            npm install

            echo "=== Writing frontend .env ==="
            cat <<EOF > ~/Apex-Auto/frontend/.env
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            EOF

            echo "=== Building frontend ==="
            npm run build

            echo "=== Configuring Nginx ==="
            sudo rm -f /etc/nginx/sites-enabled/default
            cat <<'EOF' | sudo tee /etc/nginx/sites-available/apex-auto
            server {
                listen 80;
                server_name apexauto.duckdns.org;

                root /home/ubuntu/Apex-Auto/frontend/dist;
                index index.html index.htm;

                location /api/ {
                    proxy_pass http://localhost:5000/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                }

                location / {
                    try_files $uri /index.html;
                }
            }
            EOF

            sudo ln -sf /etc/nginx/sites-available/apex-auto /etc/nginx/sites-enabled/apex-auto
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl enable nginx

            echo "✅ Deployment completed successfully!"
